#
# Dummy action to test different types of configurations
#

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ vars.REPOSITORY }}  # as <account>/<repo>


name: Docker Image CI

jobs:

  Docker:

    runs-on: ["self-hosted", "m92p"]
    environment: Docker
    permissions:
      contents: read
      packages: write
      id-token: write 
      # This is used to complete the identity challenge with sigstore/fulcio when running outside of PRs.

    steps:

    # https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v4

    # https://github.com/docker/metadata-action
    - name: Docker metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: safebytelabsjgonf/github-selfhosted-runner
        tags: |
          type=schedule
          type=sha 
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

    # https://github.com/sigstore/cosign-installer
    - name: Install cosign
      uses: sigstore/cosign-installer@v3.4.0
      with:
        cosign-release: 'v2.2.3' # optional

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # https://github.com/docker/login-action
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64, linux/arm64, linux/arm/v7

    # https://github.com/docker/build-push-action
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64, linux/arm64, linux/arm/v7
        push: true
        tags: safebytelabsjgonf/github-selfhosted-runner:latest
