#
# Dummy action to test different types of configurations
#

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ vars.REPOSITORY }}  # as <account>/<repo>


name: Docker Image CI

jobs:

  Docker:

    runs-on: ["self-hosted", "m92p"]
    environment: env_test_helloworld

    steps:

    # https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v4

    # https://github.com/docker/metadata-action
    - name: Docker metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: safebytelabsjgonf/test_helloworld
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha 
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # https://github.com/docker/login-action
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64

    # https://github.com/docker/build-push-action
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        # tags: safebytelabsjgonf/test_helloworld
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
